In [1]:
print(5)

5


In [5]:
a = np.arange(25).reshape(5,5)
y = []
for i in np.nditer(a):
  y.append(i)

print(y)  

[array(0), array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15), array(16), array(17), array(18), array(19), array(20), array(21), array(22), array(23), array(24)]


In [1]:
import numpy as np

In [6]:
import numpy as np
arr8 = np.arange(24).reshape(6,4)
arr8[0::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [10]:
a = np.zeros((2,3),dtype = int)
print(a)
l = np.identity(5)
l

[[0 0 0]
 [0 0 0]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
k = np.linspace(20,30)
print(k)
print(k.dtype)

[20.         20.20408163 20.40816327 20.6122449  20.81632653 21.02040816
 21.2244898  21.42857143 21.63265306 21.83673469 22.04081633 22.24489796
 22.44897959 22.65306122 22.85714286 23.06122449 23.26530612 23.46938776
 23.67346939 23.87755102 24.08163265 24.28571429 24.48979592 24.69387755
 24.89795918 25.10204082 25.30612245 25.51020408 25.71428571 25.91836735
 26.12244898 26.32653061 26.53061224 26.73469388 26.93877551 27.14285714
 27.34693878 27.55102041 27.75510204 27.95918367 28.16326531 28.36734694
 28.57142857 28.7755102  28.97959184 29.18367347 29.3877551  29.59183673
 29.79591837 30.        ]
float64


In [33]:
ar = np.arange(25).reshape(1,5,5)
print(ar.ndim)
print(ar)
print(ar.size)

3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]
25


In [34]:
import time
x = range(100000)
y = range(100000,200000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time() - start_time)

0.1295146942138672


In [15]:
np.empty(20).reshape(4,5)

array([[2.42154176e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.42335219e-315],
       [0.00000000e+000, 0.00000000e+000, 6.06875655e-319,
        0.00000000e+000, 0.00000000e+000],
       [2.42335243e-315, 0.00000000e+000, 2.42335187e-315,
        2.42335199e-315, 0.00000000e+000],
       [2.42335211e-315, 2.42335223e-315, 0.00000000e+000,
        2.42335235e-315, 4.94065646e-324]])

In [14]:
np.empty(10)

array([2.41017179e-315, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       8.48798316e-313, 6.02984931e+174, 1.74254810e-076, 5.28327749e-091,
       2.70248094e-056, 6.71959493e-310])

In [8]:
import numpy as np

arr12 = np.arange(24).reshape(8,3)
arr12[:2]

array([[0, 1, 2],
       [3, 4, 5]])